# (PART) Syllabus {-}

# Course Introduction

> The function of sociology, as of every science, is to reveal that which is hidden.

**Pierre Bourdieu (1996)**

</br>

This course will survey the field of sociology, stressing important ideas, methods, and results. We focus on health to illustrate the application of sociological ideas. The survey is designed to develop analytic thinking skills. Weekly readings from a text will be supplemented with articles and chapters illustrating topical issues and exercises on the skills and craft of the social sciences.

## Course Objectives

By the *end* of the semester, you should be able to:

  1. Describe the major theoretical traditions within sociology and the way that we use social theory, and apply these theories to current events.
  2. Identify sociological contributions to a number of substantive areas, including urban sociology, crime and deviance, race, class, and gender.
  3. Apply core sociological concepts by analyzing data and your own experiences to understand how they reflect fundamental social issues.
  4. Integrate core sociological concepts into analyses of population health and health disparities using both fundamental cause theory and the social determinants of health perspective as well as other sociological concepts and data.

## Cultural Diversity Core Requirement

This course fulfills the College of Arts and Sciences core requirement for Cultural Diversity in the United States. The Cultural Diversity in the United States requirement is designed to help students gain a better understanding of the cultural groups in the United States and their interactions. Students who complete a Cultural Diversity course in this category will gain a substantial subset of the following skills:

1.  Analyze and evaluate how various underrepresented social groups confront inequality and claim a just place in society.

2.  Examine how conflict and cooperation between social groups shapes U.S. society and culture.

3.  Identify how individual and institutional forms of discrimination impact leaders, communities and community building through the examination of such factors as race, ethnicity, gender, religion, economic class, age, physical and mental capability, and sexual orientation.

4.  Evaluate how their personal life experiences and choices fit within the larger mosaic of U.S. society by confronting and critically analyzing their own values and assumptions about individuals and groups from different cultural contexts.

5.  Understand how questions of diversity intersect with moral and political questions of justice and equality.

## Blackboard

**<a href = "https://blackboard.slu.edu" target = "_blank">Blackboard</a>** is a learning management system similar to Google Classroom and Canvas. There are two main areas - the `Annoucements` page and the various "modules" that contain course content. The `Annoucements` contains posts for announcements and assignments. Additions to the `Annoucements` should be emailed to your student e-mail account automatically. This will be my primary means for communicating with the class as a whole. Assignments posted to the various modules will allow you to submit work for the course.

## Readings

There are two books required for this course. Each book has been selected to correspond with one or more of the course objectives. The books are:

1.  Abraham, Laurie K. 2019. *Mama Might Be Better Off Dead: The Failure of Health Care in Urban America*. Chicago, IL: The University of Chicago Press. ISBN-13: 978-0226623702; List Price: $20.00; e-book versions available.
    * I do not require students to buy physical copies of *Mama Might Be Better Off Dead.* You are free to select a means for accessing *Mama* that meets your budget and learning style.

2. Khan, Shamus, Patrick Sharkey, and Gwen Sharp, eds. *<a href = "https://www.sociologyexperiment.com" target = "_blank">A Sociology Experiment</a>*; e-book only.
    * This is a unique "textbook" where you purchase it by chapter instead of buying the entire book. Each chapter is written by one or more leading sociologists in the fields that the chapter covers. Each chapter costs $1. If you have a concern about accessing this non-traditional resource, please let me know as soon as possible.
    * Once you purchase a chapter, you will be able to download a `.pdf` copy of the text to keep.
    * You will need to purchase the following Chapters:
      * All of Part 1- "1 - A Sociology Experiment," "2 - Research Methods," and "3- Social Structure and the Individual"
      * All of Part 2 - "4 - Social Class, Inequality, and Poverty," "5 - Culture," "6 - Gender and Sexuality," and "7 - Race and Ethnicity"
      * From Part 3 - "12 - Urban Sociology" and "15 - Health and Illness"

```{block, type = "rmdwarning"}
Only *Mama Might Be Better Off Dead* is available through the bookstore! Use <a href = "https://www.sociologyexperiment.com" target = "_blank">this link</a> or the link below to access *<a href = "https://www.sociologyexperiment.com" target = "_blank">A Sociology Experiment</a>*! All chapters can be purchased through the text's website.
```

All readings are listed on the [**Reading List**](/syllabus/lecture-schedule.html) and should be completed before the course meeting on the week in which they are assigned (unless otherwise noted). 

Many of the readings on the syllabus are peer reviewed journal articles that you'll be able to access through the library. Being "peer reviewed" means that they are written with an aim to contribute to scientific debates. Their primary audiences are typically health care providers, professors, and graduate students. They are therefore sometimes *difficult* to read. Give yourself time - I don't expect each student to fully understanding the intricacies of each article (especially the statistics included in some), but I do expect you to walk away with a general sense of the argument and evidence presented.
