# Success in SOC 1120

Since this course will meet remotely for the entire semester, I have posted several articles on the <a href = "https://slu-soc1120.github.io/docs/start_around/" target = "_blank">Course Docs</a> that include suggestions for <a href = "" target = "_blank">navigating the course content</a>,  <a href = "" target = "_blank">using Zoom</a>, and <a href = "" target = "_blank">using Blackboard</a>. Please review these before the semester begins. Following these will be crucial for having a successful semester!

Students often ask me how to do well in various aspects of the course, and so I also have *suggestions* for a successful semester. *These observations are provided with no warranty* - following them does not guarantee any particular outcome. You could do everything in here and still do poorly in the course, and conversely you could ignore much of what is in discussed in the links below and still do well. However, *most* of the students who are successful in this course will follow *most* of these ideas consistently.

These tips are an effort to illuminate what sociologists refer to as the "[hidden curriculum](https://books.google.com/books?hl=en&lr=&id=5r-TAgAAQBAJ&oi=fnd&pg=PP1&dq=hidden+curriculum#v=onepage&q=hidden%20curriculum&f=false)" of higher education - there are things you need to do to be successful, but they are often unstated or not clearly communicated.

Since I give this advice out in multiple classes, the documents themselves are stored on my [personal website](https://chris-prener.github.io):

1. [Doing the Little Things Right](https://chris-prener.github.io/resources/students/little-things/)
2. [Come to Office Hours!](https://chris-prener.github.io/resources/students/office-hours/)
3. [Studying for Exams](https://chris-prener.github.io/resources/students/exams/) (you can ignore the bit about short answer questions, since we won’t have any this semester)
4. [Writing in the Social Sciences](https://chris-prener.github.io/resources/students/writing/)
5. [Letters of Recommendation](https://chris-prener.github.io/resources/students/exams/) - Pay particular to the section titled "[If I Say No](https://chris-prener.github.io/resources/students/letters/#if-i-say-no)" if you may want an Instructor Evaluation for medical school - I prioritize letter writing for students who I get to know outside of the classroom.

If there are other topics you have questions about, please let me know. These documents are a work in progress.

```{block, type = "rmdnote"}
Part of these documents involve tips for emailing faculty and link to an article with some additional tips. If you send me an email prior to the second lecture that breaks as many rules as possible (but clearly identifies in some way who you are), I'll give you extra credit.
```
